#ifndef TIPOERROR_H
#define TIPOERROR_H

enum class TipoError : int {
    SIN_ERROR,
    BRUJA_SUPREMA_YA_EXISTE,
    BRUJA_SUPREMA_NO_EXISTE,
    BRUJA_COMUN_YA_EXISTE,
    BRUJA_NO_ES_SUPREMA,
    BRUJA_NO_EXISTE,
    MAXIMO_HECHIZOS_ALCANZADO
};

#endif // TIPOERROR_H
