//
// Created by User on 14/11/2023.
//

#ifndef OBLIGATORIO2023AMS_HECHIZOSAPRENDIDOS_H
#define OBLIGATORIO2023AMS_HECHIZOSAPRENDIDOS_H


class HechizosAprendidos {

};


#endif //OBLIGATORIO2023AMS_HECHIZOSAPRENDIDOS_H
